INSERT INTO roles (id, name) 
VALUES 
(8, 'SITE_SUPERADMIN'),
(7, 'SITE_ADMIN'),
(6, 'SITE_MOD'),
(5, 'SITE_PROJECTLEAD'),
(4, 'SITE_SCIENTIST'),
(3, 'SITE_HERO'),
(2, 'SITE_POWERUSER'),
(1, 'SITE_USER');